apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: netpol-builder-dev
spec:
  generators:
    - git:
        repoURL: https://github.com/ralvares/netpol-builder
        revision: HEAD
        directories:
          - path: "dev/*/"    # <â€” This cluster only sees DEV workloads

  template:
    metadata:
      name: netpol-builder-dev-{{path[1]}}
    spec:
      project: default

      destination:
        name: in-cluster
        namespace: {{path[1]}}

      source:
        repoURL: https://github.com/ralvares/netpol-builder
        targetRevision: HEAD
        path: charts/netpol-builder
        helm:
          valueFiles:
            - ../../dev/{{path[1]}}/values.yaml

      syncPolicy:
        automated:
          prune: true
          selfHeal: true